import Head from 'next/head'
import React from "react";
import AppLayout from "@/components/AppLayout/AppLayout";
import styled from "@emotion/styled";
import {Box, Button} from "@mui/material";
import {ChatList} from "@/components/ChatList/ChatList";
import {MessagesList} from "@/components/MessagesList/MessagesList";
import {ChatInput} from "@/components/ChatInput/ChatInput";
import {pt3} from "@/utils/styleVariables";
import {ChatHeader} from "@/components/ChatHeader/ChatHeader";
import {ChatMedia} from "@/components/ChatMedia/ChatMedia";

const StyledMain = styled.main`
  justify-content: start;
  height: 100vh;
  display: flex;
  flex-direction: row;
  align-items: stretch;
  margin: 0;
  overflow-y: auto;
`

const StyledFriendsButton = styled(Button)`
  width: 100%;
  margin-top: ${pt3};
`

export default function Index() { //page as a link for redirect to initial application route
    const [openChat, setOpenChat] = React.useState(false);
    const [openMedia, setOpenMedia] = React.useState(false);

    const handleChatOpen = () => {
        setOpenChat(true);
    };

    const handleChatClose = () => {
        setOpenChat(false);
    };

    const handleMediaOpen = () => {
        setOpenMedia(true);
    };

    const handleMediaClose = () => {
        setOpenMedia(false);
    };
    return (
        <>
            <Head>
                <title>Jointly</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <StyledMain>
                    <Box
                        sx={{
                            height: '100%',
                            overflowY: 'hidden',
                            display: 'flex',
                            flexDirection: 'column',
                            flexShrink: "1",
                        }}
                    >
                        <StyledFriendsButton variant="text">Friends</StyledFriendsButton>
                        <ChatList handleChatOpen={handleChatOpen}/>
                    </Box>
                    {openChat && <>
                        <Box
                            sx={{
                                height: '100%',
                                overflowY: 'hidden',
                                display: 'flex',
                                flexDirection: 'column',
                                flexGrow: '1',
                                padding: '0'
                            }}
                        >
                            <ChatHeader handleMediaOpen={handleMediaOpen} handleChatClose={handleChatClose}/>
                            <MessagesList/>
                            <ChatInput/>
                        </Box>
                    </>}
                    {openMedia && <ChatMedia handleMediaClose={handleMediaClose} isOpen={openMedia}/>}
                </StyledMain>
            </AppLayout>
        </>
    )
}
