import Head from 'next/head'
import React from "react";
import AppLayout from "@/components/AppLayout/AppLayout";
import styled from "@emotion/styled";

const StyledMain = styled.main`
  align-items: center;
`

export default function Index() { //page as a link for redirect to initial application route
    return (
        <>
            <Head>
                <title>Jointly</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AppLayout>
                <StyledMain>
                    <h1>Index page</h1>
                </StyledMain>
            </AppLayout>
        </>
    )
}
