import Head from 'next/head'
import styles from '@/styles/Index.module.scss'
import PromoLayout from "@/components/promoLayout/promoLayout";
import React from "react";

export default function Index() {
    return (
        <>
            <Head>
                <title>Jointly</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <PromoLayout>
                <main className={styles.main}>
                    <h1>Index page</h1>
                </main>
            </PromoLayout>
        </>
    )
}
