import Head from 'next/head'
import PromoLayout from "@/components/PromoLayout/PromoLayout";
import React from "react";
import styled from "@emotion/styled";

const StyledMain = styled.main`
  align-items: center;
`

export default function Index() {
    return (
        <>
            <Head>
                <title>Jointly</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <PromoLayout>
                <StyledMain>
                    <h1>Index page</h1>
                </StyledMain>
            </PromoLayout>
        </>
    )
}
